name: docker-image
on:
  push:
    tags:
      - v*
  pull_request:
  workflow_dispatch:
env:
  GO111MODULE: "on"
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: go-build-bin-${{ hashFiles('**/go.mod') }}
          restore-keys: go-build-bin-
      - name: Cache lichen binary
        uses: actions/cache@v2
        with:
          path: |
            ~/go/bin/lichen
          key: ${{ runner.os }}-lichen
      - name: Build application
        id: build
        run: |
          export VERSION=$([ -z "${{ github.head_ref }}" ] && echo "${GITHUB_REF##*/}" || echo "${{ github.head_ref }}")
          echo $VERSION
          time make build-linux
          echo "::set-output name=version::$VERSION"
      - name: Scan licenses
        if: hashFiles('licenses.yml') != ''
        run: |
          test -e ~/go/bin/lichen || go install github.com/vearutop/lichen@v0.1.5
          lichen -c licenses.yml ./bin/*
      - name: Build docker image
        run: |
          docker build --progress plain -t ghcr.io/acme-corp-tech/service-starter-kit:${{ steps.build.outputs.version }} -t ghcr.io/acme-corp-tech/service-starter-kit:latest .
          docker run --rm ghcr.io/acme-corp-tech/service-starter-kit:${{ steps.build.outputs.version }} -version
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_GITHUB_TOKEN }}
      - name: Push image to Github Packages
        run: |
          docker push ghcr.io/acme-corp-tech/service-starter-kit:${{ steps.build.outputs.version }}
          [ -z "${{ github.head_ref }}" ] && docker push ghcr.io/acme-corp-tech/service-starter-kit/service:latest || echo "Not pushing latest image for PR"
